# Located at &lt;CONFIG DIRECTORY&gt;/lss/config.toml or ./lss.toml

port = 9321 # host on this port
broadcast = false # make accessible to other devices on the network
default = "duckduckgo" # the default search engine (duckduckgo, google, bing, etc.)

[engines]
homemanager = "https://home-manager-options.extranix.com/?query={s}"
# if "{s}" is not present, it will always just redirect regardless of the search terms
# now you can search for "!homemanager vim"
